/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "StripLights.h"
#include "StripLights_fonts.h"
#include "S0.h"
#include "S0_aliases.h"
#include "SW1.h"
#include "SW1_aliases.h"
#include "UART_DEB.h"
#include "UART_DEB_SPI_UART.h"
#include "UART_DEB_PINS.h"
#include "UART_DEB_SPI_UART_PVT.h"
#include "UART_DEB_PVT.h"
#include "UART_DEB_BOOT.h"
#include "isr_UART_RX.h"
#include "S1.h"
#include "S1_aliases.h"
#include "StripLights_fisr.h"
#include "StripLights_cisr.h"
#include "StripLights_Clock_1.h"
#include "StripLights_StringSel.h"
#include "UART_DEB_SCBCLK.h"
#include "UART_DEB_tx.h"
#include "UART_DEB_tx_aliases.h"
#include "UART_DEB_rx.h"
#include "UART_DEB_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

