/* Automatically generated header file */

#ifndef INCLUDED_LUT_ADDRESSES_H_
#define INCLUDED_LUT_ADDRESSES_H_

#define FR_APP_ENTRY_COUNT 0
#define FR_APP_SECTOR_START 0
#define FR_APP_SECTOR_COUNT 0
#define FR_APP_IS_SECURE 0

#define DCT_IMAGE_ENTRY_COUNT 0
#define DCT_IMAGE_SECTOR_START 0
#define DCT_IMAGE_SECTOR_COUNT 0
#define DCT_IMAGE_IS_SECURE 0

#define OTA_APP_ENTRY_COUNT 0
#define OTA_APP_SECTOR_START 0
#define OTA_APP_SECTOR_COUNT 0
#define OTA_APP_IS_SECURE 0

#define FILESYSTEM_IMAGE_ENTRY_COUNT 1
#define FILESYSTEM_IMAGE_SECTOR_START 1
#define FILESYSTEM_IMAGE_SECTOR_COUNT 104
#define FILESYSTEM_IMAGE_IS_SECURE 0

#define WIFI_FIRMWARE_ENTRY_COUNT 0
#define WIFI_FIRMWARE_SECTOR_START 0
#define WIFI_FIRMWARE_SECTOR_COUNT 0
#define WIFI_FIRMWARE_IS_SECURE 0

#define APP0_ENTRY_COUNT 0
#define APP0_SECTOR_START 0
#define APP0_SECTOR_COUNT 0
#define APP0_IS_SECURE 0

#define APP1_ENTRY_COUNT 0
#define APP1_SECTOR_START 0
#define APP1_SECTOR_COUNT 0
#define APP1_IS_SECURE 0

#define APP2_ENTRY_COUNT 0
#define APP2_SECTOR_START 0
#define APP2_SECTOR_COUNT 0
#define APP2_IS_SECURE 0


#endif /* INCLUDED_LUT_ADDRESSES_H_ */
