/*
 * GATT database definition
 */

#include "wiced_bt_gatt.h"
#include "wiced_bt_uuid.h"
#include "ble_db.h"

/******************************************************************************
 *                           GATT DATABASE STRUCTURE
 ******************************************************************************/
const uint8_t gatt_database[]=
{
        /* Primary Service 'Generic Attribute' */
        PRIMARY_SERVICE_UUID16 (HDLS_GENERIC_ATTRIBUTE, UUID_SERVICE_GATT),

        /* Primary Service 'Generic Access' */
        PRIMARY_SERVICE_UUID16 (HDLS_GENERIC_ACCESS, UUID_SERVICE_GAP),

            /* Characteristic 'Device Name' */
            CHARACTERISTIC_UUID16 (HDLC_GENERIC_ACCESS_DEVICE_NAME, HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE,
                UUID_CHARACTERISTIC_DEVICE_NAME, LEGATTDB_CHAR_PROP_READ,
                LEGATTDB_PERM_READABLE),

            /* Characteristic 'Appearance' */
            CHARACTERISTIC_UUID16 (HDLC_GENERIC_ACCESS_APPEARANCE, HDLC_GENERIC_ACCESS_APPEARANCE_VALUE,
                UUID_CHARACTERISTIC_APPEARANCE, LEGATTDB_CHAR_PROP_READ,
                LEGATTDB_PERM_READABLE),

        /* Primary Service 'controller' */
        PRIMARY_SERVICE_UUID128 (HDLS_CONTROLLER, __UUID_CONTROLLER),

            /* Characteristic 'WaterLevelLeftBLE' */
            CHARACTERISTIC_UUID128_WRITABLE (HDLC_CONTROLLER_WATERLEVELLEFTBLE, HDLC_CONTROLLER_WATERLEVELLEFTBLE_VALUE,
                __UUID_CONTROLLER_WATERLEVELLEFTBLE, LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_WRITE_NO_RESPONSE | LEGATTDB_CHAR_PROP_WRITE | LEGATTDB_CHAR_PROP_NOTIFY | LEGATTDB_CHAR_PROP_INDICATE,
                LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_CMD | LEGATTDB_PERM_WRITE_REQ),

//                /* Descriptor 'Client Characteristic Configuration' */
//                CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_CONTROLLER_WATERLEVELLEFTBLE_CLIENT_CONFIGURATION,
//                    UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ | LEGATTDB_PERM_AUTH_WRITABLE),

                /* Descriptor 'Client Characteristic Configuration' */
                CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_CONTROLLER_WATERLEVELLEFTBLE_CLIENT_CONFIGURATION,
                    UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ),


            /* Characteristic 'WaterLevelRightBLE' */
            CHARACTERISTIC_UUID128_WRITABLE (HDLC_CONTROLLER_WATERLEVELRIGHTBLE, HDLC_CONTROLLER_WATERLEVELRIGHTBLE_VALUE,
                __UUID_CONTROLLER_WATERLEVELRIGHTBLE, LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_WRITE_NO_RESPONSE | LEGATTDB_CHAR_PROP_WRITE | LEGATTDB_CHAR_PROP_NOTIFY | LEGATTDB_CHAR_PROP_INDICATE,
                LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_CMD | LEGATTDB_PERM_WRITE_REQ),

//                /* Descriptor 'Client Characteristic Configuration' */
//                CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_CONTROLLER_WATERLEVELRIGHTBLE_CLIENT_CONFIGURATION,
//                    UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ | LEGATTDB_PERM_AUTH_WRITABLE),

                /* Descriptor 'Client Characteristic Configuration' */
                CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_CONTROLLER_WATERLEVELRIGHTBLE_CLIENT_CONFIGURATION,
                    UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ),

            /* Characteristic 'PumpLeftBLE' */
            CHARACTERISTIC_UUID128_WRITABLE (HDLC_CONTROLLER_PUMPLEFTBLE, HDLC_CONTROLLER_PUMPLEFTBLE_VALUE,
                __UUID_CONTROLLER_PUMPLEFTBLE, LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_WRITE_NO_RESPONSE | LEGATTDB_CHAR_PROP_WRITE,
                LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_CMD | LEGATTDB_PERM_WRITE_REQ),

            /* Characteristic 'PumpRightBLE' */
            CHARACTERISTIC_UUID128_WRITABLE (HDLC_CONTROLLER_PUMPRIGHTBLE, HDLC_CONTROLLER_PUMPRIGHTBLE_VALUE,
                __UUID_CONTROLLER_PUMPRIGHTBLE, LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_WRITE_NO_RESPONSE | LEGATTDB_CHAR_PROP_WRITE,
                LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_CMD | LEGATTDB_PERM_WRITE_REQ),
};

// Length of the GATT database
const uint16_t gatt_database_len = sizeof(gatt_database);
