/*******************************************************************************
* File Name: cycfg_peripherals.h
*
* Description:
* Peripheral Hardware Block configuration
* This file should not be modified. It was automatically generated by 
* ModusToolbox 1.0.0
* 
********************************************************************************
* Copyright (c) 2017-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#if !defined(CYCFG_PERIPHERALS_H)
#define CYCFG_PERIPHERALS_H

#include "cycfg_notices.h"
#include "cy_scb_uart.h"
#include "cy_sysclk.h"
#include "cy_smif.h"

#if defined(__cplusplus)
extern "C" {
#endif

#define scb_5_HW SCB5
#define scb_5_IRQ scb_5_interrupt_IRQn
#define smif_HW SMIF0
#define smif_IRQ smif_interrupt_IRQn
#define smif_MEMORY_MODE_ALIGMENT_ERROR (0UL)
#define smif_RX_DATA_FIFO_UNDERFLOW (0UL)
#define smif_TX_COMMAND_FIFO_OVERFLOW (0UL)
#define smif_TX_DATA_FIFO_OVERFLOW (0UL)
#define smif_RX_FIFO_TRIGEER_LEVEL (0UL)
#define smif_TX_FIFO_TRIGEER_LEVEL (0UL)
#define smif_DATALINES0_1 (1UL)
#define smif_DATALINES2_3 (1UL)
#define smif_DATALINES4_5 (0UL)
#define smif_DATALINES6_7 (0UL)
#define smif_SS0 (1UL)
#define smif_SS1 (0UL)
#define smif_SS2 (0UL)
#define smif_SS3 (0UL)
#define smif_DESELECT_DELAY 7

extern const cy_stc_scb_uart_config_t scb_5_config;
extern const cy_stc_smif_config_t smif_config;

void init_cycfg_peripherals(void);

#if defined(__cplusplus)
}
#endif


#endif /* CYCFG_PERIPHERALS_H */
