/*******************************************************************************
* File Name: cycfg_connectivity.h
*
* Description:
* Establishes all necessary connections between hardware elements.
* This file should not be modified. It was automatically generated by 
* ModusToolbox 1.0.0
* 
********************************************************************************
* Copyright (c) 2017-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cy_device_headers.h"

#include "stdbool.h"

#include "cy_trigmux.h"

#include "cycfg_connectivity.h"

void init_cycfg_connectivity(void)
{
	Cy_TrigMux_Connect(TRIG_IN_MUX_0_TCPWM0_TR_COMPARE_MATCH0, TRIG_OUT_MUX_0_PDMA0_TR_IN5, false, TRIGGER_TYPE_EDGE);
	Cy_TrigMux_Connect(TRIG_IN_MUX_2_PDMA0_TR_OUT5, TRIG_OUT_MUX_2_TCPWM0_TR_IN6, false, TRIGGER_TYPE_EDGE);
	HSIOM->AMUX_SPLIT_CTL[5] = HSIOM_V2_AMUX_SPLIT_CTL_SWITCH_AA_SR_Msk |
		HSIOM_V2_AMUX_SPLIT_CTL_SWITCH_AA_SL_Msk |
		HSIOM_V2_AMUX_SPLIT_CTL_SWITCH_BB_SR_Msk |
		HSIOM_V2_AMUX_SPLIT_CTL_SWITCH_BB_SL_Msk;
	HSIOM->AMUX_SPLIT_CTL[6] = HSIOM_V2_AMUX_SPLIT_CTL_SWITCH_AA_SL_Msk |
		HSIOM_V2_AMUX_SPLIT_CTL_SWITCH_AA_SR_Msk |
		HSIOM_V2_AMUX_SPLIT_CTL_SWITCH_BB_SL_Msk |
		HSIOM_V2_AMUX_SPLIT_CTL_SWITCH_BB_SR_Msk;
	HSIOM->AMUX_SPLIT_CTL[4] = HSIOM_V2_AMUX_SPLIT_CTL_SWITCH_AA_SL_Msk |
		HSIOM_V2_AMUX_SPLIT_CTL_SWITCH_AA_SR_Msk |
		HSIOM_V2_AMUX_SPLIT_CTL_SWITCH_BB_SL_Msk |
		HSIOM_V2_AMUX_SPLIT_CTL_SWITCH_BB_SR_Msk;
	HSIOM->AMUX_SPLIT_CTL[2] = HSIOM_V2_AMUX_SPLIT_CTL_SWITCH_AA_SR_Msk |
		HSIOM_V2_AMUX_SPLIT_CTL_SWITCH_AA_SL_Msk |
		HSIOM_V2_AMUX_SPLIT_CTL_SWITCH_BB_SR_Msk |
		HSIOM_V2_AMUX_SPLIT_CTL_SWITCH_BB_SL_Msk;
}
