/*******************************************************************************
* File Name: cycfg_connectivity.h
*
* Description:
* Establishes all necessary connections between hardware elements.
* This file should not be modified. It was automatically generated by 
* ModusToolbox 1.0.0
* 
********************************************************************************
* Copyright (c) 2017-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#if !defined(CYCFG_CONNECTIVITY_H)
#define CYCFG_CONNECTIVITY_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "cycfg_notices.h"
void init_cycfg_connectivity(void);

#define ioss_0_port_0_pin_2_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_10_pin_1_HSIOM P10_1_SCB1_UART_TX
#define ioss_0_port_10_pin_6_HSIOM P10_6_TCPWM0_LINE1
#define ioss_0_port_11_pin_2_HSIOM P11_2_TCPWM1_LINE2
#define ioss_0_port_13_pin_0_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_13_pin_1_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_13_pin_6_HSIOM P13_6_TCPWM0_LINE3
#define ioss_0_port_1_pin_2_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_1_pin_3_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_1_pin_4_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_1_pin_5_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_2_pin_0_HSIOM P2_0_SDHC0_CARD_DAT_3TO00
#define ioss_0_port_2_pin_1_HSIOM P2_1_SDHC0_CARD_DAT_3TO01
#define ioss_0_port_2_pin_2_HSIOM P2_2_SDHC0_CARD_DAT_3TO02
#define ioss_0_port_2_pin_3_HSIOM P2_3_SDHC0_CARD_DAT_3TO03
#define ioss_0_port_2_pin_4_HSIOM P2_4_SDHC0_CARD_CMD
#define ioss_0_port_2_pin_5_HSIOM P2_5_SDHC0_CLK_CARD
#define ioss_0_port_5_pin_0_HSIOM P5_0_SCB5_UART_RX
#define ioss_0_port_5_pin_1_HSIOM P5_1_SCB5_UART_TX
#define ioss_0_port_5_pin_4_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_5_pin_5_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_5_pin_6_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_6_pin_4_HSIOM P6_4_CPUSS_SWJ_SWO_TDO
#define ioss_0_port_6_pin_6_HSIOM P6_6_CPUSS_SWJ_SWDIO_TMS
#define ioss_0_port_6_pin_7_HSIOM P6_7_CPUSS_SWJ_SWCLK_TCLK
#define ioss_0_port_7_pin_1_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_7_pin_2_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_7_pin_3_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_7_pin_6_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_8_pin_0_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_8_pin_1_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_8_pin_2_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_8_pin_3_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_8_pin_4_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_8_pin_5_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_8_pin_6_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_8_pin_7_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_9_pin_0_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_9_pin_1_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_9_pin_2_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_9_pin_3_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_9_pin_4_HSIOM HSIOM_SEL_AMUXB
#define ioss_0_port_9_pin_5_HSIOM HSIOM_SEL_AMUXB

#if defined(__cplusplus)
}
#endif


#endif /* CYCFG_CONNECTIVITY_H */
