/*******************************************************************************
* File Name: cycfg_pins.h
*
* Description:
* Pin configuration
* This file should not be modified. It was automatically generated by 
* ModusToolbox 1.0.0
* 
********************************************************************************
* Copyright (c) 2017-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#if !defined(CYCFG_PINS_H)
#define CYCFG_PINS_H

#include "cycfg_notices.h"
#include "cy_gpio.h"
#include "cycfg_connectivity.h"

#if defined(__cplusplus)
extern "C" {
#endif

#define ioss_0_port_0_pin_2_PORT GPIO_PRT0
#define ioss_0_port_0_pin_2_PIN 2U
#define ioss_0_port_0_pin_2_NUM 2U
#define ioss_0_port_0_pin_2_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_0_pin_2_INIT_DRIVESTATE 1
#ifndef ioss_0_port_0_pin_2_HSIOM
	#define ioss_0_port_0_pin_2_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_0_pin_2_IRQ ioss_interrupts_gpio_0_IRQn
#define LED_RED_PORT GPIO_PRT0
#define LED_RED_PIN 3U
#define LED_RED_NUM 3U
#define LED_RED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_RED_INIT_DRIVESTATE 1
#ifndef ioss_0_port_0_pin_3_HSIOM
	#define ioss_0_port_0_pin_3_HSIOM HSIOM_SEL_GPIO
#endif
#define LED_RED_HSIOM ioss_0_port_0_pin_3_HSIOM
#define LED_RED_IRQ ioss_interrupts_gpio_0_IRQn
#define startLED_PORT GPIO_PRT10
#define startLED_PIN 0U
#define startLED_NUM 0U
#define startLED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define startLED_INIT_DRIVESTATE 0
#ifndef ioss_0_port_10_pin_0_HSIOM
	#define ioss_0_port_10_pin_0_HSIOM HSIOM_SEL_GPIO
#endif
#define startLED_HSIOM ioss_0_port_10_pin_0_HSIOM
#define startLED_IRQ ioss_interrupts_gpio_10_IRQn
#define ioss_0_port_10_pin_1_PORT GPIO_PRT10
#define ioss_0_port_10_pin_1_PIN 1U
#define ioss_0_port_10_pin_1_NUM 1U
#define ioss_0_port_10_pin_1_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define ioss_0_port_10_pin_1_INIT_DRIVESTATE 1
#ifndef ioss_0_port_10_pin_1_HSIOM
	#define ioss_0_port_10_pin_1_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_10_pin_1_IRQ ioss_interrupts_gpio_10_IRQn
#define armLED_PORT GPIO_PRT10
#define armLED_PIN 2U
#define armLED_NUM 2U
#define armLED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define armLED_INIT_DRIVESTATE 0
#ifndef ioss_0_port_10_pin_2_HSIOM
	#define ioss_0_port_10_pin_2_HSIOM HSIOM_SEL_GPIO
#endif
#define armLED_HSIOM ioss_0_port_10_pin_2_HSIOM
#define armLED_IRQ ioss_interrupts_gpio_10_IRQn
#define pumpEnable_PORT GPIO_PRT10
#define pumpEnable_PIN 3U
#define pumpEnable_NUM 3U
#define pumpEnable_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define pumpEnable_INIT_DRIVESTATE 1
#ifndef ioss_0_port_10_pin_3_HSIOM
	#define ioss_0_port_10_pin_3_HSIOM HSIOM_SEL_GPIO
#endif
#define pumpEnable_HSIOM ioss_0_port_10_pin_3_HSIOM
#define pumpEnable_IRQ ioss_interrupts_gpio_10_IRQn
#define rightPumpIN2_PORT GPIO_PRT10
#define rightPumpIN2_PIN 4U
#define rightPumpIN2_NUM 4U
#define rightPumpIN2_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define rightPumpIN2_INIT_DRIVESTATE 1
#ifndef ioss_0_port_10_pin_4_HSIOM
	#define ioss_0_port_10_pin_4_HSIOM HSIOM_SEL_GPIO
#endif
#define rightPumpIN2_HSIOM ioss_0_port_10_pin_4_HSIOM
#define rightPumpIN2_IRQ ioss_interrupts_gpio_10_IRQn
#define rightPumpIN1_PORT GPIO_PRT10
#define rightPumpIN1_PIN 5U
#define rightPumpIN1_NUM 5U
#define rightPumpIN1_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define rightPumpIN1_INIT_DRIVESTATE 1
#ifndef ioss_0_port_10_pin_5_HSIOM
	#define ioss_0_port_10_pin_5_HSIOM HSIOM_SEL_GPIO
#endif
#define rightPumpIN1_HSIOM ioss_0_port_10_pin_5_HSIOM
#define rightPumpIN1_IRQ ioss_interrupts_gpio_10_IRQn
#define ioss_0_port_10_pin_6_PORT GPIO_PRT10
#define ioss_0_port_10_pin_6_PIN 6U
#define ioss_0_port_10_pin_6_NUM 6U
#define ioss_0_port_10_pin_6_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define ioss_0_port_10_pin_6_INIT_DRIVESTATE 1
#ifndef ioss_0_port_10_pin_6_HSIOM
	#define ioss_0_port_10_pin_6_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_10_pin_6_IRQ ioss_interrupts_gpio_10_IRQn
#define BLUE_LED_PORT GPIO_PRT11
#define BLUE_LED_PIN 1U
#define BLUE_LED_NUM 1U
#define BLUE_LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define BLUE_LED_INIT_DRIVESTATE 1
#ifndef ioss_0_port_11_pin_1_HSIOM
	#define ioss_0_port_11_pin_1_HSIOM HSIOM_SEL_GPIO
#endif
#define BLUE_LED_HSIOM ioss_0_port_11_pin_1_HSIOM
#define BLUE_LED_IRQ ioss_interrupts_gpio_11_IRQn
#define ioss_0_port_11_pin_2_PORT GPIO_PRT11
#define ioss_0_port_11_pin_2_PIN 2U
#define ioss_0_port_11_pin_2_NUM 2U
#define ioss_0_port_11_pin_2_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define ioss_0_port_11_pin_2_INIT_DRIVESTATE 1
#ifndef ioss_0_port_11_pin_2_HSIOM
	#define ioss_0_port_11_pin_2_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_11_pin_2_IRQ ioss_interrupts_gpio_11_IRQn
#define ioss_0_port_13_pin_0_PORT GPIO_PRT13
#define ioss_0_port_13_pin_0_PIN 0U
#define ioss_0_port_13_pin_0_NUM 0U
#define ioss_0_port_13_pin_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_13_pin_0_INIT_DRIVESTATE 1
#ifndef ioss_0_port_13_pin_0_HSIOM
	#define ioss_0_port_13_pin_0_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_13_pin_0_IRQ ioss_interrupts_gpio_13_IRQn
#define ioss_0_port_13_pin_1_PORT GPIO_PRT13
#define ioss_0_port_13_pin_1_PIN 1U
#define ioss_0_port_13_pin_1_NUM 1U
#define ioss_0_port_13_pin_1_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_13_pin_1_INIT_DRIVESTATE 1
#ifndef ioss_0_port_13_pin_1_HSIOM
	#define ioss_0_port_13_pin_1_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_13_pin_1_IRQ ioss_interrupts_gpio_13_IRQn
#define WIFI_RESET_PORT GPIO_PRT13
#define WIFI_RESET_PIN 5U
#define WIFI_RESET_NUM 5U
#define WIFI_RESET_DRIVEMODE CY_GPIO_DM_ANALOG
#define WIFI_RESET_INIT_DRIVESTATE 1
#ifndef ioss_0_port_13_pin_5_HSIOM
	#define ioss_0_port_13_pin_5_HSIOM HSIOM_SEL_GPIO
#endif
#define WIFI_RESET_HSIOM ioss_0_port_13_pin_5_HSIOM
#define WIFI_RESET_IRQ ioss_interrupts_gpio_13_IRQn
#define ioss_0_port_13_pin_6_PORT GPIO_PRT13
#define ioss_0_port_13_pin_6_PIN 6U
#define ioss_0_port_13_pin_6_NUM 6U
#define ioss_0_port_13_pin_6_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define ioss_0_port_13_pin_6_INIT_DRIVESTATE 1
#ifndef ioss_0_port_13_pin_6_HSIOM
	#define ioss_0_port_13_pin_6_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_13_pin_6_IRQ ioss_interrupts_gpio_13_IRQn
#define GREEN_LED_PORT GPIO_PRT1
#define GREEN_LED_PIN 1U
#define GREEN_LED_NUM 1U
#define GREEN_LED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define GREEN_LED_INIT_DRIVESTATE 1
#ifndef ioss_0_port_1_pin_1_HSIOM
	#define ioss_0_port_1_pin_1_HSIOM HSIOM_SEL_GPIO
#endif
#define GREEN_LED_HSIOM ioss_0_port_1_pin_1_HSIOM
#define GREEN_LED_IRQ ioss_interrupts_gpio_1_IRQn
#define ioss_0_port_1_pin_2_PORT GPIO_PRT1
#define ioss_0_port_1_pin_2_PIN 2U
#define ioss_0_port_1_pin_2_NUM 2U
#define ioss_0_port_1_pin_2_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_1_pin_2_INIT_DRIVESTATE 1
#ifndef ioss_0_port_1_pin_2_HSIOM
	#define ioss_0_port_1_pin_2_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_1_pin_2_IRQ ioss_interrupts_gpio_1_IRQn
#define ioss_0_port_1_pin_3_PORT GPIO_PRT1
#define ioss_0_port_1_pin_3_PIN 3U
#define ioss_0_port_1_pin_3_NUM 3U
#define ioss_0_port_1_pin_3_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_1_pin_3_INIT_DRIVESTATE 1
#ifndef ioss_0_port_1_pin_3_HSIOM
	#define ioss_0_port_1_pin_3_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_1_pin_3_IRQ ioss_interrupts_gpio_1_IRQn
#define ioss_0_port_1_pin_4_PORT GPIO_PRT1
#define ioss_0_port_1_pin_4_PIN 4U
#define ioss_0_port_1_pin_4_NUM 4U
#define ioss_0_port_1_pin_4_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_1_pin_4_INIT_DRIVESTATE 1
#ifndef ioss_0_port_1_pin_4_HSIOM
	#define ioss_0_port_1_pin_4_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_1_pin_4_IRQ ioss_interrupts_gpio_1_IRQn
#define ioss_0_port_1_pin_5_PORT GPIO_PRT1
#define ioss_0_port_1_pin_5_PIN 5U
#define ioss_0_port_1_pin_5_NUM 5U
#define ioss_0_port_1_pin_5_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_1_pin_5_INIT_DRIVESTATE 1
#ifndef ioss_0_port_1_pin_5_HSIOM
	#define ioss_0_port_1_pin_5_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_1_pin_5_IRQ ioss_interrupts_gpio_1_IRQn
#define SDHC0_DAT0_PORT GPIO_PRT2
#define SDHC0_DAT0_PIN 0U
#define SDHC0_DAT0_NUM 0U
#define SDHC0_DAT0_DRIVEMODE CY_GPIO_DM_STRONG
#define SDHC0_DAT0_INIT_DRIVESTATE 1
#ifndef ioss_0_port_2_pin_0_HSIOM
	#define ioss_0_port_2_pin_0_HSIOM HSIOM_SEL_GPIO
#endif
#define SDHC0_DAT0_HSIOM ioss_0_port_2_pin_0_HSIOM
#define SDHC0_DAT0_IRQ ioss_interrupts_gpio_2_IRQn
#define SDHC0_DAT1_PORT GPIO_PRT2
#define SDHC0_DAT1_PIN 1U
#define SDHC0_DAT1_NUM 1U
#define SDHC0_DAT1_DRIVEMODE CY_GPIO_DM_STRONG
#define SDHC0_DAT1_INIT_DRIVESTATE 1
#ifndef ioss_0_port_2_pin_1_HSIOM
	#define ioss_0_port_2_pin_1_HSIOM HSIOM_SEL_GPIO
#endif
#define SDHC0_DAT1_HSIOM ioss_0_port_2_pin_1_HSIOM
#define SDHC0_DAT1_IRQ ioss_interrupts_gpio_2_IRQn
#define SDHC0_DAT2_PORT GPIO_PRT2
#define SDHC0_DAT2_PIN 2U
#define SDHC0_DAT2_NUM 2U
#define SDHC0_DAT2_DRIVEMODE CY_GPIO_DM_STRONG
#define SDHC0_DAT2_INIT_DRIVESTATE 1
#ifndef ioss_0_port_2_pin_2_HSIOM
	#define ioss_0_port_2_pin_2_HSIOM HSIOM_SEL_GPIO
#endif
#define SDHC0_DAT2_HSIOM ioss_0_port_2_pin_2_HSIOM
#define SDHC0_DAT2_IRQ ioss_interrupts_gpio_2_IRQn
#define SDHC0_DAT3_PORT GPIO_PRT2
#define SDHC0_DAT3_PIN 3U
#define SDHC0_DAT3_NUM 3U
#define SDHC0_DAT3_DRIVEMODE CY_GPIO_DM_STRONG
#define SDHC0_DAT3_INIT_DRIVESTATE 1
#ifndef ioss_0_port_2_pin_3_HSIOM
	#define ioss_0_port_2_pin_3_HSIOM HSIOM_SEL_GPIO
#endif
#define SDHC0_DAT3_HSIOM ioss_0_port_2_pin_3_HSIOM
#define SDHC0_DAT3_IRQ ioss_interrupts_gpio_2_IRQn
#define SDHC0_CMD_PORT GPIO_PRT2
#define SDHC0_CMD_PIN 4U
#define SDHC0_CMD_NUM 4U
#define SDHC0_CMD_DRIVEMODE CY_GPIO_DM_STRONG
#define SDHC0_CMD_INIT_DRIVESTATE 1
#ifndef ioss_0_port_2_pin_4_HSIOM
	#define ioss_0_port_2_pin_4_HSIOM HSIOM_SEL_GPIO
#endif
#define SDHC0_CMD_HSIOM ioss_0_port_2_pin_4_HSIOM
#define SDHC0_CMD_IRQ ioss_interrupts_gpio_2_IRQn
#define SDHC0_CLK_PORT GPIO_PRT2
#define SDHC0_CLK_PIN 5U
#define SDHC0_CLK_NUM 5U
#define SDHC0_CLK_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define SDHC0_CLK_INIT_DRIVESTATE 1
#ifndef ioss_0_port_2_pin_5_HSIOM
	#define ioss_0_port_2_pin_5_HSIOM HSIOM_SEL_GPIO
#endif
#define SDHC0_CLK_HSIOM ioss_0_port_2_pin_5_HSIOM
#define SDHC0_CLK_IRQ ioss_interrupts_gpio_2_IRQn
#define ioss_0_port_2_pin_6_PORT GPIO_PRT2
#define ioss_0_port_2_pin_6_PIN 6U
#define ioss_0_port_2_pin_6_NUM 6U
#define ioss_0_port_2_pin_6_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define ioss_0_port_2_pin_6_INIT_DRIVESTATE 0
#ifndef ioss_0_port_2_pin_6_HSIOM
	#define ioss_0_port_2_pin_6_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_2_pin_6_IRQ ioss_interrupts_gpio_2_IRQn
#define UART_RX_PORT GPIO_PRT5
#define UART_RX_PIN 0U
#define UART_RX_NUM 0U
#define UART_RX_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_RX_INIT_DRIVESTATE 1
#ifndef ioss_0_port_5_pin_0_HSIOM
	#define ioss_0_port_5_pin_0_HSIOM HSIOM_SEL_GPIO
#endif
#define UART_RX_HSIOM ioss_0_port_5_pin_0_HSIOM
#define UART_RX_IRQ ioss_interrupts_gpio_5_IRQn
#define UART_TX_PORT GPIO_PRT5
#define UART_TX_PIN 1U
#define UART_TX_NUM 1U
#define UART_TX_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_TX_INIT_DRIVESTATE 1
#ifndef ioss_0_port_5_pin_1_HSIOM
	#define ioss_0_port_5_pin_1_HSIOM HSIOM_SEL_GPIO
#endif
#define UART_TX_HSIOM ioss_0_port_5_pin_1_HSIOM
#define UART_TX_IRQ ioss_interrupts_gpio_5_IRQn
#define ioss_0_port_5_pin_4_PORT GPIO_PRT5
#define ioss_0_port_5_pin_4_PIN 4U
#define ioss_0_port_5_pin_4_NUM 4U
#define ioss_0_port_5_pin_4_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_5_pin_4_INIT_DRIVESTATE 1
#ifndef ioss_0_port_5_pin_4_HSIOM
	#define ioss_0_port_5_pin_4_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_5_pin_4_IRQ ioss_interrupts_gpio_5_IRQn
#define ioss_0_port_5_pin_5_PORT GPIO_PRT5
#define ioss_0_port_5_pin_5_PIN 5U
#define ioss_0_port_5_pin_5_NUM 5U
#define ioss_0_port_5_pin_5_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_5_pin_5_INIT_DRIVESTATE 1
#ifndef ioss_0_port_5_pin_5_HSIOM
	#define ioss_0_port_5_pin_5_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_5_pin_5_IRQ ioss_interrupts_gpio_5_IRQn
#define ioss_0_port_5_pin_6_PORT GPIO_PRT5
#define ioss_0_port_5_pin_6_PIN 6U
#define ioss_0_port_5_pin_6_NUM 6U
#define ioss_0_port_5_pin_6_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_5_pin_6_INIT_DRIVESTATE 1
#ifndef ioss_0_port_5_pin_6_HSIOM
	#define ioss_0_port_5_pin_6_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_5_pin_6_IRQ ioss_interrupts_gpio_5_IRQn
#define leftPumpIN1_PORT GPIO_PRT6
#define leftPumpIN1_PIN 2U
#define leftPumpIN1_NUM 2U
#define leftPumpIN1_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define leftPumpIN1_INIT_DRIVESTATE 1
#ifndef ioss_0_port_6_pin_2_HSIOM
	#define ioss_0_port_6_pin_2_HSIOM HSIOM_SEL_GPIO
#endif
#define leftPumpIN1_HSIOM ioss_0_port_6_pin_2_HSIOM
#define leftPumpIN1_IRQ ioss_interrupts_gpio_6_IRQn
#define leftPumpIN2_PORT GPIO_PRT6
#define leftPumpIN2_PIN 3U
#define leftPumpIN2_NUM 3U
#define leftPumpIN2_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define leftPumpIN2_INIT_DRIVESTATE 1
#ifndef ioss_0_port_6_pin_3_HSIOM
	#define ioss_0_port_6_pin_3_HSIOM HSIOM_SEL_GPIO
#endif
#define leftPumpIN2_HSIOM ioss_0_port_6_pin_3_HSIOM
#define leftPumpIN2_IRQ ioss_interrupts_gpio_6_IRQn
#define SWO_PORT GPIO_PRT6
#define SWO_PIN 4U
#define SWO_NUM 4U
#define SWO_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define SWO_INIT_DRIVESTATE 1
#ifndef ioss_0_port_6_pin_4_HSIOM
	#define ioss_0_port_6_pin_4_HSIOM HSIOM_SEL_GPIO
#endif
#define SWO_HSIOM ioss_0_port_6_pin_4_HSIOM
#define SWO_IRQ ioss_interrupts_gpio_6_IRQn
#define SWDIO_PORT GPIO_PRT6
#define SWDIO_PIN 6U
#define SWDIO_NUM 6U
#define SWDIO_DRIVEMODE CY_GPIO_DM_PULLUP
#define SWDIO_INIT_DRIVESTATE 1
#ifndef ioss_0_port_6_pin_6_HSIOM
	#define ioss_0_port_6_pin_6_HSIOM HSIOM_SEL_GPIO
#endif
#define SWDIO_HSIOM ioss_0_port_6_pin_6_HSIOM
#define SWDIO_IRQ ioss_interrupts_gpio_6_IRQn
#define SWCLK_PORT GPIO_PRT6
#define SWCLK_PIN 7U
#define SWCLK_NUM 7U
#define SWCLK_DRIVEMODE CY_GPIO_DM_PULLDOWN
#define SWCLK_INIT_DRIVESTATE 1
#ifndef ioss_0_port_6_pin_7_HSIOM
	#define ioss_0_port_6_pin_7_HSIOM HSIOM_SEL_GPIO
#endif
#define SWCLK_HSIOM ioss_0_port_6_pin_7_HSIOM
#define SWCLK_IRQ ioss_interrupts_gpio_6_IRQn
#define ioss_0_port_7_pin_1_PORT GPIO_PRT7
#define ioss_0_port_7_pin_1_PIN 1U
#define ioss_0_port_7_pin_1_NUM 1U
#define ioss_0_port_7_pin_1_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_7_pin_1_INIT_DRIVESTATE 1
#ifndef ioss_0_port_7_pin_1_HSIOM
	#define ioss_0_port_7_pin_1_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_7_pin_1_IRQ ioss_interrupts_gpio_7_IRQn
#define ioss_0_port_7_pin_2_PORT GPIO_PRT7
#define ioss_0_port_7_pin_2_PIN 2U
#define ioss_0_port_7_pin_2_NUM 2U
#define ioss_0_port_7_pin_2_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_7_pin_2_INIT_DRIVESTATE 1
#ifndef ioss_0_port_7_pin_2_HSIOM
	#define ioss_0_port_7_pin_2_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_7_pin_2_IRQ ioss_interrupts_gpio_7_IRQn
#define ioss_0_port_7_pin_3_PORT GPIO_PRT7
#define ioss_0_port_7_pin_3_PIN 3U
#define ioss_0_port_7_pin_3_NUM 3U
#define ioss_0_port_7_pin_3_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_7_pin_3_INIT_DRIVESTATE 1
#ifndef ioss_0_port_7_pin_3_HSIOM
	#define ioss_0_port_7_pin_3_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_7_pin_3_IRQ ioss_interrupts_gpio_7_IRQn
#define startButton_PORT GPIO_PRT7
#define startButton_PIN 4U
#define startButton_NUM 4U
#define startButton_DRIVEMODE CY_GPIO_DM_PULLUP
#define startButton_INIT_DRIVESTATE 1
#ifndef ioss_0_port_7_pin_4_HSIOM
	#define ioss_0_port_7_pin_4_HSIOM HSIOM_SEL_GPIO
#endif
#define startButton_HSIOM ioss_0_port_7_pin_4_HSIOM
#define startButton_IRQ ioss_interrupts_gpio_7_IRQn
#define armSwitch_PORT GPIO_PRT7
#define armSwitch_PIN 5U
#define armSwitch_NUM 5U
#define armSwitch_DRIVEMODE CY_GPIO_DM_PULLUP
#define armSwitch_INIT_DRIVESTATE 1
#ifndef ioss_0_port_7_pin_5_HSIOM
	#define ioss_0_port_7_pin_5_HSIOM HSIOM_SEL_GPIO
#endif
#define armSwitch_HSIOM ioss_0_port_7_pin_5_HSIOM
#define armSwitch_IRQ ioss_interrupts_gpio_7_IRQn
#define ioss_0_port_7_pin_6_PORT GPIO_PRT7
#define ioss_0_port_7_pin_6_PIN 6U
#define ioss_0_port_7_pin_6_NUM 6U
#define ioss_0_port_7_pin_6_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_7_pin_6_INIT_DRIVESTATE 1
#ifndef ioss_0_port_7_pin_6_HSIOM
	#define ioss_0_port_7_pin_6_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_7_pin_6_IRQ ioss_interrupts_gpio_7_IRQn
#define ioss_0_port_8_pin_0_PORT GPIO_PRT8
#define ioss_0_port_8_pin_0_PIN 0U
#define ioss_0_port_8_pin_0_NUM 0U
#define ioss_0_port_8_pin_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_8_pin_0_INIT_DRIVESTATE 1
#ifndef ioss_0_port_8_pin_0_HSIOM
	#define ioss_0_port_8_pin_0_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_8_pin_0_IRQ ioss_interrupts_gpio_8_IRQn
#define ioss_0_port_8_pin_1_PORT GPIO_PRT8
#define ioss_0_port_8_pin_1_PIN 1U
#define ioss_0_port_8_pin_1_NUM 1U
#define ioss_0_port_8_pin_1_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_8_pin_1_INIT_DRIVESTATE 1
#ifndef ioss_0_port_8_pin_1_HSIOM
	#define ioss_0_port_8_pin_1_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_8_pin_1_IRQ ioss_interrupts_gpio_8_IRQn
#define ioss_0_port_8_pin_2_PORT GPIO_PRT8
#define ioss_0_port_8_pin_2_PIN 2U
#define ioss_0_port_8_pin_2_NUM 2U
#define ioss_0_port_8_pin_2_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_8_pin_2_INIT_DRIVESTATE 1
#ifndef ioss_0_port_8_pin_2_HSIOM
	#define ioss_0_port_8_pin_2_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_8_pin_2_IRQ ioss_interrupts_gpio_8_IRQn
#define ioss_0_port_8_pin_3_PORT GPIO_PRT8
#define ioss_0_port_8_pin_3_PIN 3U
#define ioss_0_port_8_pin_3_NUM 3U
#define ioss_0_port_8_pin_3_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_8_pin_3_INIT_DRIVESTATE 1
#ifndef ioss_0_port_8_pin_3_HSIOM
	#define ioss_0_port_8_pin_3_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_8_pin_3_IRQ ioss_interrupts_gpio_8_IRQn
#define ioss_0_port_8_pin_4_PORT GPIO_PRT8
#define ioss_0_port_8_pin_4_PIN 4U
#define ioss_0_port_8_pin_4_NUM 4U
#define ioss_0_port_8_pin_4_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_8_pin_4_INIT_DRIVESTATE 1
#ifndef ioss_0_port_8_pin_4_HSIOM
	#define ioss_0_port_8_pin_4_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_8_pin_4_IRQ ioss_interrupts_gpio_8_IRQn
#define ioss_0_port_8_pin_5_PORT GPIO_PRT8
#define ioss_0_port_8_pin_5_PIN 5U
#define ioss_0_port_8_pin_5_NUM 5U
#define ioss_0_port_8_pin_5_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_8_pin_5_INIT_DRIVESTATE 1
#ifndef ioss_0_port_8_pin_5_HSIOM
	#define ioss_0_port_8_pin_5_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_8_pin_5_IRQ ioss_interrupts_gpio_8_IRQn
#define ioss_0_port_8_pin_6_PORT GPIO_PRT8
#define ioss_0_port_8_pin_6_PIN 6U
#define ioss_0_port_8_pin_6_NUM 6U
#define ioss_0_port_8_pin_6_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_8_pin_6_INIT_DRIVESTATE 1
#ifndef ioss_0_port_8_pin_6_HSIOM
	#define ioss_0_port_8_pin_6_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_8_pin_6_IRQ ioss_interrupts_gpio_8_IRQn
#define ioss_0_port_8_pin_7_PORT GPIO_PRT8
#define ioss_0_port_8_pin_7_PIN 7U
#define ioss_0_port_8_pin_7_NUM 7U
#define ioss_0_port_8_pin_7_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_8_pin_7_INIT_DRIVESTATE 1
#ifndef ioss_0_port_8_pin_7_HSIOM
	#define ioss_0_port_8_pin_7_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_8_pin_7_IRQ ioss_interrupts_gpio_8_IRQn
#define ioss_0_port_9_pin_0_PORT GPIO_PRT9
#define ioss_0_port_9_pin_0_PIN 0U
#define ioss_0_port_9_pin_0_NUM 0U
#define ioss_0_port_9_pin_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_9_pin_0_INIT_DRIVESTATE 1
#ifndef ioss_0_port_9_pin_0_HSIOM
	#define ioss_0_port_9_pin_0_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_9_pin_0_IRQ ioss_interrupts_gpio_9_IRQn
#define ioss_0_port_9_pin_1_PORT GPIO_PRT9
#define ioss_0_port_9_pin_1_PIN 1U
#define ioss_0_port_9_pin_1_NUM 1U
#define ioss_0_port_9_pin_1_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_9_pin_1_INIT_DRIVESTATE 1
#ifndef ioss_0_port_9_pin_1_HSIOM
	#define ioss_0_port_9_pin_1_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_9_pin_1_IRQ ioss_interrupts_gpio_9_IRQn
#define ioss_0_port_9_pin_2_PORT GPIO_PRT9
#define ioss_0_port_9_pin_2_PIN 2U
#define ioss_0_port_9_pin_2_NUM 2U
#define ioss_0_port_9_pin_2_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_9_pin_2_INIT_DRIVESTATE 1
#ifndef ioss_0_port_9_pin_2_HSIOM
	#define ioss_0_port_9_pin_2_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_9_pin_2_IRQ ioss_interrupts_gpio_9_IRQn
#define ioss_0_port_9_pin_3_PORT GPIO_PRT9
#define ioss_0_port_9_pin_3_PIN 3U
#define ioss_0_port_9_pin_3_NUM 3U
#define ioss_0_port_9_pin_3_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_9_pin_3_INIT_DRIVESTATE 1
#ifndef ioss_0_port_9_pin_3_HSIOM
	#define ioss_0_port_9_pin_3_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_9_pin_3_IRQ ioss_interrupts_gpio_9_IRQn
#define ioss_0_port_9_pin_4_PORT GPIO_PRT9
#define ioss_0_port_9_pin_4_PIN 4U
#define ioss_0_port_9_pin_4_NUM 4U
#define ioss_0_port_9_pin_4_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_9_pin_4_INIT_DRIVESTATE 1
#ifndef ioss_0_port_9_pin_4_HSIOM
	#define ioss_0_port_9_pin_4_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_9_pin_4_IRQ ioss_interrupts_gpio_9_IRQn
#define ioss_0_port_9_pin_5_PORT GPIO_PRT9
#define ioss_0_port_9_pin_5_PIN 5U
#define ioss_0_port_9_pin_5_NUM 5U
#define ioss_0_port_9_pin_5_DRIVEMODE CY_GPIO_DM_ANALOG
#define ioss_0_port_9_pin_5_INIT_DRIVESTATE 1
#ifndef ioss_0_port_9_pin_5_HSIOM
	#define ioss_0_port_9_pin_5_HSIOM HSIOM_SEL_GPIO
#endif
#define ioss_0_port_9_pin_5_IRQ ioss_interrupts_gpio_9_IRQn
#define audioMute_PORT GPIO_PRT9
#define audioMute_PIN 6U
#define audioMute_NUM 6U
#define audioMute_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW_IN_OFF
#define audioMute_INIT_DRIVESTATE 1
#ifndef ioss_0_port_9_pin_6_HSIOM
	#define ioss_0_port_9_pin_6_HSIOM HSIOM_SEL_GPIO
#endif
#define audioMute_HSIOM ioss_0_port_9_pin_6_HSIOM
#define audioMute_IRQ ioss_interrupts_gpio_9_IRQn

extern const cy_stc_gpio_pin_config_t ioss_0_port_0_pin_2_config;
extern const cy_stc_gpio_pin_config_t LED_RED_config;
extern const cy_stc_gpio_pin_config_t startLED_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_10_pin_1_config;
extern const cy_stc_gpio_pin_config_t armLED_config;
extern const cy_stc_gpio_pin_config_t pumpEnable_config;
extern const cy_stc_gpio_pin_config_t rightPumpIN2_config;
extern const cy_stc_gpio_pin_config_t rightPumpIN1_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_10_pin_6_config;
extern const cy_stc_gpio_pin_config_t BLUE_LED_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_11_pin_2_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_13_pin_0_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_13_pin_1_config;
extern const cy_stc_gpio_pin_config_t WIFI_RESET_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_13_pin_6_config;
extern const cy_stc_gpio_pin_config_t GREEN_LED_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_1_pin_2_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_1_pin_3_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_1_pin_4_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_1_pin_5_config;
extern const cy_stc_gpio_pin_config_t SDHC0_DAT0_config;
extern const cy_stc_gpio_pin_config_t SDHC0_DAT1_config;
extern const cy_stc_gpio_pin_config_t SDHC0_DAT2_config;
extern const cy_stc_gpio_pin_config_t SDHC0_DAT3_config;
extern const cy_stc_gpio_pin_config_t SDHC0_CMD_config;
extern const cy_stc_gpio_pin_config_t SDHC0_CLK_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_2_pin_6_config;
extern const cy_stc_gpio_pin_config_t UART_RX_config;
extern const cy_stc_gpio_pin_config_t UART_TX_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_5_pin_4_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_5_pin_5_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_5_pin_6_config;
extern const cy_stc_gpio_pin_config_t leftPumpIN1_config;
extern const cy_stc_gpio_pin_config_t leftPumpIN2_config;
extern const cy_stc_gpio_pin_config_t SWO_config;
extern const cy_stc_gpio_pin_config_t SWDIO_config;
extern const cy_stc_gpio_pin_config_t SWCLK_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_7_pin_1_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_7_pin_2_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_7_pin_3_config;
extern const cy_stc_gpio_pin_config_t startButton_config;
extern const cy_stc_gpio_pin_config_t armSwitch_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_7_pin_6_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_8_pin_0_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_8_pin_1_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_8_pin_2_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_8_pin_3_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_8_pin_4_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_8_pin_5_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_8_pin_6_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_8_pin_7_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_9_pin_0_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_9_pin_1_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_9_pin_2_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_9_pin_3_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_9_pin_4_config;
extern const cy_stc_gpio_pin_config_t ioss_0_port_9_pin_5_config;
extern const cy_stc_gpio_pin_config_t audioMute_config;

void init_cycfg_pins(void);

#if defined(__cplusplus)
}
#endif


#endif /* CYCFG_PINS_H */
